volumes:
  postgres_volume_chat_server:

services:
  pg-chat:
    image: postgres:16-alpine3.20
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT_OUTER}:${PG_PORT_INNER}"
    volumes:
      - postgres_volume_chat_server:/var/lib/postgresql/data
    networks:
      - messanger-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE_NAME} -h 127.0.0.1 || exit 1"]
      interval: 2s
      timeout: 1s
      retries: 15
      start_period: 5s
       
  migrator:
    build:
      context: .
      dockerfile: migrator.Dockerfile

    restart: on-failure
    environment:
        DB_HOST: pg-chat
    env_file: .env
    networks:
      - messanger-network
    depends_on:
      pg-chat:
        condition: service_healthy

  chat-server:
    build: .
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
      - "${HTTP_PORT}:${HTTP_PORT}"
    restart: unless-stopped
    env_file: .env
    networks:
      - messanger-network
    depends_on:
      pg-chat:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

networks:
  messanger-network:
    external: true

